command: ["npm", "run", "start"]
runtime: nodejs20

# OAuth scopes required for OBO (On-Behalf-Of) authentication
# These scopes allow the app to call APIs using the user's credentials
user_api_scopes:
  - serving.serving-endpoints  # Required to call serving endpoints
  - sql                        # Optional: for SQL operations
  - catalog.catalogs:read      # Optional: for catalog access
  - catalog.schemas:read       # Optional: for schema access
  - catalog.tables:read        # Optional: for table access

env:
  - name: DATABRICKS_SERVING_ENDPOINT
    valueFrom: serving-endpoint
  - name: PGHOST
    value: instance-7a2538b2-2809-42a7-922e-a8f76e3d08db.database.cloud.databricks.com
  - name: PGUSER
    valueFrom: current-user
  - name: PGDATABASE
    value: databricks_postgres
  - name: PGPORT
    value: "5432"
  - name: PGSSLMODE
    value: require
